#
# See https://docs.rubocop.org/rubocop/configuration
#
---
AllCops:
  Exclude:
    - 'db/schema.rb'
  NewCops: disable
  EnabledByDefault: false
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/PredicateName:
  Exclude:
    - 'app/lib/node_extensions.rb'

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoreMacros: true

Style/BlockDelimiters:
  Enabled: false
