---
version: "3"

x-app-defaults: &app-defaults
  image: "ghcr.io/pabloscolpino/lingua-finder:development"
  entrypoint: bin/docker-entrypoint.sh
  volumes:
    - .:/app
    - bundler:/bundler
    - node_modules:/app/node_modules

services:
  web:
    <<: *app-defaults
    build:
      context: .
      target: development
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "13000:3000"
    command: bundle exec rails server -b 0.0.0.0

  cypress:
    image: cypress/included:10.3.0
    command: open --project /app
    entrypoint: cypress
    stdin_open: true
    tty: true
    depends_on:
      - web
    environment:
      CYPRESS_baseUrl: http://web:3000
      DISPLAY: ${CYPRESS_DISPLAY}
    working_dir: /app
    volumes:
      - ./:/app
      - /tmp/.X11-unix/:/tmp/.X11-unix

  worker:
    <<: *app-defaults
    command: bundle exec sidekiq
    environment:
      SIDEKIQ_WORKERS: 2
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:14.5
    # image: bitnami/postgresql:14.5.0
    environment:
      POSTGRES_USER: lingua-finder
      POSTGRES_PASSWORD: lingua-finder
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0.2
    # image: bitnami/mongodb:6.0.2
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0.5
    # image: bitnami/redis:7.0.5
    environment:
      REDIS_PASSWORD: lingua-finder
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  mongo-data:
  redis-data:
  bundler:
  node_modules:
