version: "3"

x-rails-app-defaults: &rails-app-defaults
  image: "lingua-finder:${TAG}"
  entrypoint: bin/docker-entrypoint.sh
  volumes:
    - .:/app:cached
    - bundler:/bundler:cached
    - node_modules:/app/node_modules:cached

services:
  web:
    <<: *rails-app-defaults
    build:
      context: .
      target: development
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "13000:3000"
    command: bundle exec rails server -b 0.0.0.0

  worker:
    <<: *rails-app-defaults
    depends_on:
      - postgres
      - mongodb
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:9.6.15-alpine
    environment:
      POSTGRES_USER: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  mongo-data:
  redis-data:
  bundler:
  node_modules:
