---
version: "3"

x-app-defaults: &app-defaults
  image: "ghcr.io/pabloscolpino/lingua-finder:development"
  stdin_open: true
  tty: true
  entrypoint: bin/docker-entrypoint.sh
  volumes:
    - .:/app
    - bundler:/bundler
    - node_modules:/app/node_modules

services:
  web:
    <<: *app-defaults
    build:
      context: .
      target: development
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "13000:3000"
    command: bundle exec rails server -b 0.0.0.0

  web-cypress:
    <<: *app-defaults
    build:
      context: .
      target: development
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      CYPRESS: 1
    command: bundle exec rails server -b 0.0.0.0 --pid /app/tmp/cypress-s.pid

  cypress:
    <<: *app-defaults
    command: yarn run cypress open --project /app --e2e --browser electron
    depends_on:
      - web-cypress
    entrypoint: bin/cypress-entrypoint.sh
    environment:
      CYPRESS_baseUrl: http://web-cypress:3000
      DISPLAY: ${CYPRESS_DISPLAY}
      CYPRESS_CACHE_FOLDER: /app/node_modules/.cypress_cache

  worker:
    <<: *app-defaults
    command: bundle exec sidekiq
    environment:
      SIDEKIQ_WORKERS: 2
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:14.5
    # image: bitnami/postgresql:14.5.0
    environment:
      POSTGRES_USER: lingua-finder
      POSTGRES_PASSWORD: lingua-finder
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0.2
    # image: bitnami/mongodb:6.0.2
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0.5
    # image: bitnami/redis:7.0.5
    environment:
      REDIS_PASSWORD: lingua-finder
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  mongo-data:
  redis-data:
  bundler:
  node_modules:
  cypress_cache:
