version: "3"

x-app-defaults: &app-defaults
  image: "ghcr.io/pabloscolpino/lingua-finder:latest"
  environment:
    DATABASE_URL: postgres://postgres@postgres/lingua_finder_p
    MONGODB_URI: mongodb://mongodb/lingua_finder_p
    REDIS_URL: redis://redis/0
    PORT: 3000
    RAILS_MAX_WORKERS: 1
    RAILS_LOG_TO_STDOUT: true
    DB_POOL: 20
    SIDEKIQ_WORKERS: 2
    SECRET_KEY_BASE: some-very-big-secret

    GOOGLE_API_KEY: a-key
    GOOGLE_SEARCH_CX: a-search-cx

    OA2_GOOGLE_CLIENT_ID: a-client-id
    OA2_GOOGLE_CLIENT_SECRET: a-secret


services:
  web:
    <<: *app-defaults
    build:
      context: .
      target: production
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "13000:3000"
    command: bundle exec rails server -b 0.0.0.0

  worker:
    <<: *app-defaults
    depends_on:
      - postgres
      - mongodb
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:9.6.15-alpine
    environment:
      POSTGRES_USER: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  mongo-data:
  redis-data:
