version: "3"

x-app-defaults: &app-defaults
  image: "ghcr.io/pabloscolpino/lingua-finder:development"
  entrypoint: bin/docker-entrypoint.sh
  volumes:
    - .:/app
    - bundler:/bundler
    - node_modules:/app/node_modules

services:
  web:
    <<: *app-defaults
    build:
      context: .
      target: development
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "13000:3000"
    command: bundle exec rails server -b 0.0.0.0

  worker:
    <<: *app-defaults
    command: bundle exec sidekiq
    environment:
      SIDEKIQ_WORKERS: 2
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:9.6.15-alpine
    environment:
      POSTGRES_USER: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  mongo-data:
  redis-data:
  bundler:
  node_modules:
