default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5 %>
  variables:
    statement_timeout: <%= ENV["DB_TIMEOUT"] || 5000 %>

development:
  <<: *default
  database: lingua_finder_dev
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: lingua_finder_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: lingua_finder_prod
  url: <%= ENV['DATABASE_URL'] %>
