development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: <%= ENV['MONGODB_TIMEOUT'] %>
        max_pool_size: <%= ENV['MONGODB_MAX_POOL_SIZE'] %>

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        max_pool_size: 1

staging:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: <%= ENV['MONGODB_TIMEOUT'] %>
        max_pool_size: <%= ENV['MONGODB_MAX_POOL_SIZE'] %>

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: <%= ENV['MONGODB_TIMEOUT'] %>
        max_pool_size: <%= ENV['MONGODB_MAX_POOL_SIZE'] %>
