---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  PORT: "80"
  RAILS_MAX_WORKERS: "5"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  DB_POOL: "30"
  SIDEKIQ_WORKERS: "10"
