---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lingua-finder.fullname" . }}
  labels:
    {{- include "lingua-finder.labels" . | nindent 4 }}
data:
  PORT: "80"
  RAILS_MAX_WORKERS: "2"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  DB_POOL: "20"
  SIDEKIQ_WORKERS: "2"
