apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: lingua-finder
  name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.15-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
          volumeMounts:
            - name: lingua-finder-postgres
              mountPath: /var/lib/postgresql/data
