name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  RUBY_VERSION: 2.4.4
  BUNDLER_VERSION: 1.16.6

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

  test:
    needs: setup
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.15
        ports: ["5432:5432"]
      redis:
        image: redis
        ports: ["6379:6379"]
      mongodb:
        image: mongo:4.2
        ports: ["27017:27017"]

    steps:
      - name: Setup Database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres@localhost/lingua_finder_test
        run: bin/rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          REDIS_URL: redis://localhost
          DATABASE_URL: postgres://postgres@localhost/lingua_finder_test
          MONGODB_URI: mongodb://localhost/lingua_finder_test
        run: bundle exec rspec

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3

