name: CI

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.15
        ports: ["5432:5432"]
      redis:
        image: redis
        ports: ["6379:6379"]
      mongodb:
        image: mongo:4.2
        ports: ["27017:27017"]

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres@localhost/lingua_finder_test
        run: bin/rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          REDIS_URL: redis://localhost
          DATABASE_URL: postgres://postgres@localhost/lingua_finder_test
          MONGODB_URI: mongodb://localhost/lingua_finder_test
        run: bundle exec rspec

      - name: Upload coverage results
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
