---
name: CI

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build development image
        uses: docker/build-push-action@v4
        with:
          push: false
          target: development
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build production image
        uses: docker/build-push-action@v4
        with:
          push: false
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.15
        ports: ["5432:5432"]
      redis:
        image: redis:7.0.5
        ports: ["6379:6379"]
      mongodb:
        image: mongo:6.0.2
        ports: ["27017:27017"]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres@localhost/lingua_finder_test
        run: bundle exec rake db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          REDIS_URL: redis://localhost/0
          DATABASE_URL: postgres://postgres@localhost/lingua_finder_test
          MONGODB_URI: mongodb://localhost/lingua_finder_test
        run: bundle exec rspec --format RSpec::Github::Formatter

      - name: Upload coverage results
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
